# Generated by Django 5.2.8 on 2025-11-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_message",
                    models.TextField(help_text="The user's message or prompt."),
                ),
                (
                    "agent_response",
                    models.TextField(help_text="The agent's generated response."),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time the interaction occurred.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Log",
                "verbose_name_plural": "Chat Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
