# Generated by Django 5.2.8 on 2025-11-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("tech_stack", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image for the project.",
                        null=True,
                        upload_to="project_images/",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Use this if you are hosting the image externally.",
                    ),
                ),
                ("link", models.URLField(blank=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Projects with a lower number will be displayed first.",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "title"],
            },
        ),
    ]
