# Generated by Django 5.2.8 on 2025-11-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
