# Generated by Django 5.2.8 on 2025-11-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_contactmessage_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
