# Generated by Django 5.2.8 on 2025-11-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_alter_contactmessage_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
