# Generated by Django 5.2.8 on 2026-05-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_project_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload your resume PDF.", upload_to="resumes/"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Resume File",
                "verbose_name_plural": "Resume Files",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
