"""
Django settings for abdullafajal project.

Generated by 'django-admin startproject' using Django 4.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


load_dotenv() # Load environment variables from .env file
def str_to_bool(value):
    return value.lower() in ("true", "1", "t", "yes", "True")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-88!z%nsl^+$5&u$7i207q%zuese=x3o87p4drkh7)0%t5s(bl=")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = str_to_bool(os.environ.get("DEBUG", "True"))

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "portfolio",
    "dynamic_preferences",
    "pwa",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "abdullafajal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "dynamic_preferences.processors.global_preferences",
            ],
        },
    },
]

WSGI_APPLICATION = "abdullafajal.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Email Configuration (for development)
# In production, use a real email backend like SMTP.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = str_to_bool(os.environ.get('EMAIL_USE_TLS', 'True'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'webmaster@abdullafajal.com')
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'admin@abdullafajal.com')  # This should be your actual email



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (user-uploaded content)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# PWA Settings
PWA_APP_NAME = "Abdulla Fajal"
PWA_APP_DESCRIPTION = "Abdulla Fajal's Personal Portfolio"
PWA_APP_THEME_COLOR = "#154d71"
PWA_APP_BACKGROUND_COLOR = "#EDF1F6"
PWA_APP_DISPLAY = "standalone"
PWA_APP_ORIENTATION = "portrait-primary"
PWA_APP_START_URL = "/"
PWA_APP_SCOPE = "/"
PWA_APP_ICONS = [
    {
        "src": "/static/icons/icon-72-72.png",
        "sizes": "72x72",
        "type": "image/png",
    },
    {
        "src": "/static/icons/icon-96x96.png",
        "sizes": "96x96",
        "type": "image/png",
    },
    {
        "src": "/static/icons/icon-144x144.png",
        "sizes": "144x144",
        "type": "image/png",
    },
    {
        "src": "/static/icons/icon-192-192.png",
        "sizes": "192x192",
        "type": "image/png",
    },
    {
        "src": "/static/icons/icon-512-512.png",
        "sizes": "512x512",
        "type": "image/png",
    },
]
PWA_APP_ICONS_APPLE = [
    {
        "src": "/static/icons/icon-192-192.png",
        "sizes": "192x192",
        "type": "image/png",
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        "src": "static/icons/icon-512-512.png",
        "media": "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)",
    }
]
PWA_APP_DIR = "ltr"
PWA_APP_LANG = "en-US"
PWA_APP_SHORT_NAME = "Abdulla Fajal"
PWA_APP_URLS = (
    "/",
    "/contact/",
    "/projects/",
    "/resume/",
    "/about/",
)
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, "static/serviceworker.js")

# Session settings — keep superusers logged in for 30 days
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days in seconds
SESSION_SAVE_EVERY_REQUEST = True  # Reset expiry on each request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

